#!/bin/sh
set -eux

if ! cargo fmt -- --check; then
	echo "There are some code style issues."
	echo "Run cargo fmt first."
	exit 1
fi

clippy() {
	if ! cargo clippy --all-targets "$@" -- -D warnings; then
		echo "There are some clippy issues."
		exit 1
	fi
}

clippy --no-default-features --features "tls-rustls"
clippy --no-default-features --features "tls-rustls http-interface"
clippy --no-default-features --features "tls-native-tls"
