[package]
name = "utf_nate"
version = "0.1.0"
authors = ["sampley <sampley@ualberta.ca>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
itertools = "0.8"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serenity]
version = "0.8"
features = ["builder", "cache", "client", "framework", "gateway", "http", "model", "standard_framework", "utils", "rustls_backend", "voice"]
