[package]
name = "utf_nate"
version = "0.1.0"
authors = ["sampley <sampley@ualberta.ca>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
itertools = "0.10"
futures = "0.3"
uuid = "0.8"
structopt = "0.3"
regex = "1.5"
once_cell = "1.8"
log = "0.4"
env_logger = "0.9"
walkdir = "2.3"
dashmap = "4.0"
fxhash = "0.2"
rand = "0.8"
caith = "4.2.1"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serenity]
version = "0.10"
features = ["builder", "cache", "client", "framework", "gateway", "http", "model", "standard_framework", "utils", "rustls_backend", "unstable_discord_api", "voice"]

[dependencies.tokio]
version = "1.0"
features = ["macros", "rt-multi-thread"]

[dependencies.songbird]
version = "0.2"
features = ["driver", "builtin-queue"]

[dependencies.reqwest]
version = "0.11"
features = ["json"]

[dependencies.sqlx]
version = "0.5"
default-features = false
features = ["runtime-tokio-native-tls", "postgres"]
