# List of prefixes recognized by the bot
prefixes = ["!", "?", "‽"]

# Optional activity setting of the bot
#activity = { Competing = { name = "\u2694" } }
#activity = { Listening = { name = "\U0001F3A4" } }
#activity = { Playing = { name = "\U0001F3AE" } }
#activity = { Streaming = { name = "\U0001F4FA", url = "https://www.twitch.tv/" } }
#activity = { Watching = { name = "\U0001F440" } }

# Optional http interface setup
# 0.0.0.0 can be used to just bind to the current ip
#http = { public_url = "my.domain.com:443", listen = "0.0.0.0:8080" }
