# List of prefixes recognized by the bot
prefixes = ["!", "?", "‽"]

# Optional activity setting of the bot
#activity = { Competing = { name = "\u2694" } }
#activity = { Listening = { name = "\U0001F3A4" } }
#activity = { Playing = { name = "\U0001F3AE" } }
#activity = { Streaming = { name = "\U0001F4FA", url = "https://www.twitch.tv/" } }
#activity = { Watching = { name = "\U0001F440" } }

# Optional http bind address for a web interface
# 0.0.0.0 can be used to just bind to the current ip
#http = "0.0.0.0:8080"

# Control how many requests to send concurrently while fetching a playlist
# This applies to a single request, separate requests are always concurrent
# youtube = { concurrent_request_buffer = 25 }

