[discord]
# Discord application ID
application_id = 999999999999999999
# Discord bot token
token = "xxxxxxxxxxxxxxxxxxxxxxxx.xxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[database]
# Database Connection String
connect_string = "postgresql://utf_nate:password@localhost/utf_nate"

# Optional youtube API, required for play commands
# [youtube]
# # Youtube API Key
# key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Optional spotify API information, required to support spotify links
# [spotify]
# # Spotify client ID
# client_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
# # Spotify client secret
# client_secret = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
