#!/bin/sh
ipv4=$(host -4 -W 2 myip.opendns.com resolver1.opendns.com 2>&1 | grep "myip.opendns.com" | sed 's/^.*address //')
ipv6=$(host -6 -W 2 myip.opendns.com resolver1.opendns.com 2>&1 | grep "myip.opendns.com" | sed 's/^.*address //')

if [ "$ipv4" ]; then
	echo "IPv4: \`$ipv4\`"
fi
if [ "$ipv6" ]; then
	echo "IPv6: \`$ipv6\`"
fi
if [ ! \( "$ipv4" -o "$ipv6" \) ]; then
	echo "Unable to find a public IP"
fi
